Repository carpentries/glosario, pull requests merged in 2020-12, with the labels that each got.

#236 Translate 7 terms do portuguese
  glossary.yml
Labels: lang: pt

#241 Fix incorrectly spellt tag (key)
  glossary.yml
Labels: bug

#221 define: function
  glossary.yml
Labels: lang: en, lang: ja, waiting-review

#127 Adding the terms 'Numpy' and 'SciPy' in en, pt and es, and translate Python from Portuguese and Spanish
  glossary.yml
Labels: hacktoberfest-accepted, lang: en, lang: es, lang: pt

#183 Add Spanish for absolute and relative errors
  glossary.yml
Labels: lang: es

#186 Added Spanish for agile development and exploratory programming
  glossary.yml
Labels: lang: es

#188 Added Spanish for global and local installation
  glossary.yml
Labels: lang: es

#189 Added Spanish for pseudo-random number
  glossary.yml
Labels: lang: es

#190 Added Spanish for filesystem
  glossary.yml
Labels: lang: es

#242 Translate 5 terminos a español
  glossary.yml
Labels: lang: es

#246 Add English term for algorithm
  glossary.yml
Labels: lang: en
