Repository carpentries/glosario, pull requests merged in 2020-10, with the labels that each got.

#96 More programming terms
  glossary.yml
Labels: enhancement

#93 Terms related to unit testing
  glossary.yml
Labels: enhancement

#95 Adding terms for HTTP
  glossary.yml
Labels: enhancement

#52 Translate to portuguese: path related terms
  glossary.yml
Labels: waiting-review

#106 Update glossary.yml, translations to Portuguese
  glossary.yml
Labels: waiting-review

#118 add instructions on keeping an up-to-date fork
  CONTRIBUTING.md
Labels: documentation

#133 added the Arabic translation for 4 terms
  _config.yml
  glossary.yml
Labels: lang: ar

#140 Add dir attributes to HTML templates/frontmatter
  _includes/glossary.html
  _includes/title.html
  ar.md
  glossary.yml
Labels: infrastructure

#146 use 'auto' for dir attribute
  _config.yml
  _includes/glossary.html
  _includes/title.html
  glossary.yml
  index.html
Labels: enhancement, infrastructure

#137 Translate aggregation to portuguese
  glossary.yml
Labels: hacktoberfest-accepted, lang: pt

#145 Update glossary.yml
  glossary.yml
Labels: lang: fr

#143 Add three Afrikaans terms, add <fixit> to empty terms
  glossary.yml
Labels: lang: af

#128 Translating 8 term to portuguese
  glossary.yml
Labels: lang: pt

#158 Update English term for argument and add Afrikaans translations
  glossary.yml
Labels: lang: af, lang: en

#159 Added confidence interval of Afrikaans
  glossary.yml
Labels: lang: af

#131 Spanish definitions of OOP terms and a few fixes
  glossary.yml
Labels: lang: es

#163 Translate 5 terms to Arabic
  _config.yml
  glossary.yml
Labels: lang: ar

#164 Translated SQL-related terms to French
  glossary.yml
Labels: lang: fr

#155 Translating 8 more terms to Portuguese
  glossary.yml
Labels: lang: pt

#165 Translated chi-square test to Afrikaans
  glossary.yml
Labels: lang: af

#169 Added Afrikaans terms
  glossary.yml
Labels: lang: af
