Repository carpentries/glosario, pull requests merged in 2020-11, with the labels that each got.

#147 translate git to Japanese
  glossary.yml
Labels: lang: ja

#192 Afrikaans translations
  glossary.yml
Labels: lang: af

#191 add German page
  de.md
Labels: infrastructure

#187 General editing and corrections
  glossary.yml
Labels: lang: en

#167 Translating 8 terms to Portuguese
  glossary.yml
Labels: lang: pt

#214 Afrikaans translations for argument, arithmetic_mean, ascii and asser…
  glossary.yml
Labels: lang: af

#218 Translate three terms to Arabic
  glossary.yml
Labels: lang: ar

#223 Add new term to arabic
  glossary.yml
Labels: lang: ar

#185 Translate to portuguese: OOP related terms
  glossary.yml
Labels: lang: pt

#227 Add three Afrikaans terms
  glossary.yml
Labels: lang: af

#228 Add three Afrikaans terms
  glossary.yml
Labels: lang: af
