Repository carpentries/glosario, pull requests merged in 2021-08, with the labels that each got.

#327 Definition of "browser cache" added.
  glossary.yml
Labels: lang: en

#361 [French] Add translation for 'local installation'
  glossary.yml
Labels: lang: fr

#359 [French] Add translation for 'package'
  glossary.yml
Labels: lang: fr

#358 [French] Add translation for 'module'
  glossary.yml
Labels: lang: fr

#362 Add quotes around Japanese term for 'package'
  glossary.yml
Labels: lang: ja

#357 Add definition for 'ggplot2' (English)
  glossary.yml
Labels: lang: en

#363 [French] Definition of 'local variable'
  glossary.yml
Labels: lang: fr
