Repository carpentries/glosario, pull requests merged in 2021-01, with the labels that each got.

#256 Added Afrikaans terms
  glossary.yml
Labels: lang: af

#103 Added three interlinked Spanish terms
  glossary.yml
Labels: lang: es, waiting-review

#263 Translate 5 terminos a español
  glossary.yml
Labels: lang: es
