Repository carpentries/glosario, pull requests merged in 2021-11, with the labels that each got.

#365 Translate function (German)
  glossary.yml
Labels: lang: de

#356 [German] translations for different markup languages
  glossary.yml
Labels: lang: de

#355 [German] translations for filesystem, folder, operating system
  glossary.yml
Labels: lang: de

#354 [German] standard_deviation, mean, and variance translations
  glossary.yml
Labels: lang: de

#442 Add definitions for 'sistema binario', 'ciencia de datos', and 'cientifico/cientifica de datos' (Spanish)
  glossary.yml
Labels: lang: es

#443 Modified keyword for binary in [Spanish]
  glossary.yml
Labels: lang: es

#448 Update glossary.yml
  glossary.yml
Labels: lang: id

#460 Add definition for 'node' (Afrikaans)
  glossary.yml
Labels: lang: af

#462 Updated terms into Afrikaans
  glossary.yml
Labels: lang: af

#459 Update glossary.yml
  glossary.yml
Labels: lang: af

#457 Added definitions for 'bit' and 'binary expression' (Dutch)
  glossary.yml
Labels: lang: nl
