Repository carpentries/glosario, pull requests merged in 2021-09, with the labels that each got.

#328 Add definition of 'control flow' (English)
  glossary.yml
Labels: lang: en

#364 Translate backward_compatible (German)
  glossary.yml
Labels: lang: de

#375 add German entries submitted by email
  glossary.yml
Labels: lang: de

#308 Added 'shiny' (English) definition
  glossary.yml
Labels: lang: en

#330 Added definition "source code" (English)
  glossary.yml
Labels: lang: en

#373 Updated Remote Login Setswana term
  glossary.yml
Labels: lang: tn

#381 Add definition for 'directory' in English
  glossary.yml
Labels: lang: en
