Repository carpentries/glosario, pull requests merged in 2021-04, with the labels that each got.

#288 Added definition for 'abandonware' (Bangla)
  glossary.yml
Labels: lang: bn

#154 Translate 68-95-99.7 rule to spanish
  glossary.yml
Labels: lang: es

#283 Add Spanish definition for "Secure Shell"
  glossary.yml
Labels: lang: es

#255 Add 'clustering' in Japanese and change style
  glossary.yml
Labels: lang: ja
