Repository carpentries/glosario, pull requests merged in 2022-07, with the labels that each got.

#497 Add definition for UNIX in English
  glossary.yml
Labels: lang: en

#504 Revised blurb for Dutch/Nederlands
  _config.yml
Labels: lang: nl

#493 Add German translation for library and license
  glossary.yml
Labels: lang: de

#488 Add/translate definitions for cache and browser cache (German)
  glossary.yml
Labels: lang: de

#478 Typo in algorithm (Spanish)
  glossary.yml
Labels: lang: es

#494 Translation of seed (Spanish)
  glossary.yml
Labels: lang: es

#495 Add translation for 'vignette' (Spanish)
  glossary.yml
Labels: lang: es

#210 Add the definition of lsof
  glossary.yml
Labels: lang: es, lang: en

#514 Updated contribution instructions
  README.md
Labels: enhancement

#515 Update glossary.yml
  glossary.yml
Labels: lang: tn

#516 Update glossary.yml
  glossary.yml
Labels: lang: tn
