Repository carpentries/glosario, pull requests merged in 2022-08, with the labels that each got.

#501 feat(zh): add infrastructure for Chinese
  _config.yml
  utils/check-glossary.py
  zh.md
Labels: lang: zh

#522 Add netlify and Code of Conduct links
  .gitignore
  CODE_OF_CONDUCT.md
  _layouts/glossary.html
  _layouts/page.html
Labels: documentation, enhancement

#520 Translate 3 terms (French)
  glossary.yml
Labels: lang: fr

#521 Update glossary_add definition for 'science ouverte'
  glossary.yml
Labels: lang: fr

#523 Add definitions for 'FASTA', 'FASTQ' (English)
  glossary.yml
Labels: lang: en

#524 Update glossary.yml
  glossary.yml
Labels: lang: ar

#517 Translate 21 terms (Spanish)
  glossary.yml
Labels: lang: es
