Repository carpentries/glosario, pull requests merged in 2022-03, with the labels that each got.

#437 Add definition for 'immutable type' and 'mutable type' (English)
  glossary.yml
Labels: lang: en

#435 Add English definition for "data visualization"
  glossary.yml
Labels: lang: en

#388 adding workflow (English)
  glossary.yml
Labels: lang: en

#386 Add definition for 'concatenate' (English)
  glossary.yml
Labels: lang: en

#367 Add definitions for 'True, False Positive & Negative' (English)
  glossary.yml
Labels: lang: en

#436 Add English definition for "garbage in, garbage out"
  glossary.yml
Labels: lang: en

#434 Add English definition for "algorithmic bias"
  glossary.yml
Labels: lang: en

#433 Add English definition for "data masking"
  glossary.yml
Labels: lang: en

#390 Add definition for 'factor' (English
  glossary.yml
Labels: lang: en

#385 Define IPython
  glossary.yml
Labels: lang: en

#341 Add definition for 'abstract method' (Spanish)
  glossary.yml
Labels: lang: es

#473 Translate "wildcard" to Dutch
  glossary.yml
Labels: lang: nl

#471 Add definition for 'encoding'
  glossary.yml
Labels: lang: en

#470 Add definition of 'actual error' (Spanish)
  glossary.yml
Labels: lang: es
