Repository carpentries/glosario, pull requests merged in 2022-12, with the labels that each got.

#542 Added Kiswahili translations for four terms
  glossary.yml
Labels: lang: sw

#546 Add more Kiswahili terms
  glossary.yml
Labels: lang: sw

#541 Added Kiswahili translations for ‘condition’
  glossary.yml
Labels: lang: sw

#547 Added Kiswahili Translations for 1 word
  glossary.yml
Labels: lang: sw

#548 Added Kiswahili translations for 5 words
  glossary.yml
Labels: lang: sw

#549 Added Kiswahili translations for 3 words
  glossary.yml
Labels: lang: sw

#550 Added Kiswahili translations for 6 words
  glossary.yml
Labels: lang: sw

#551 Added Kiswahili translations for 10 words
  glossary.yml
Labels: lang: sw

#553 Added Kiswahili translations for 4 words
  glossary.yml
Labels: lang: sw

#554 Added one Kiswahili word; "edge"
  glossary.yml
Labels: lang: sw

#555 Corrected typo :+ to +
  glossary.yml
Labels: lang: af

#557 Created Southern Sotho md file
  st.md
Labels: bug

#536 Four Setswana translations
  glossary.yml
Labels: lang: tn

#503 Add definition for 'python', 'algorithm' (Italian)
  glossary.yml
Labels: lang: it

#540 Translate 4 terms to Italian
  glossary.yml
Labels: lang: it

#558 Add definitions for parametric and non-parametric statistics
  glossary.yml
Labels: lang: en
