Repository carpentries/glosario, pull requests merged in 2023-01, with the labels that each got.

#560 add definition for 'high performance computing' (English)
  glossary.yml
Labels: lang: en

#562 Added Kiswahili terms
  glossary.yml
Labels: lang: sw

#563 Update glossary.yml
  glossary.yml
Labels: lang: sw

#564 Added Hungarian translation
  _config.yml
  hu.md
  utils/check-glossary.py
Labels: lang:hu

#566 Update glossary.yml
  glossary.yml
Labels: lang: sw

#565 Update glossary.yml
  glossary.yml
Labels: lang: sw
