Repository carpentries/glosario, pull requests merged in 2023-09, with the labels that each got.

#596 Update GitHub Workflows
  .github/workflows/build-and-deploy.yaml
  .github/workflows/yaml-lint.yaml
Labels: bug

#593 Update slack links
  README.md
Labels: enhancement

#599 Add term "selecting on the dependent variable bias"
  glossary.yml
Labels: lang: es, lang: en

#597 Update definition of 'specificity'
  glossary.yml
Labels: lang: en
