Repository carpentries/glosario, pull requests merged in 2023-12, with the labels that each got.

#583 Added Portuguese definition of standard normal distribution
  glossary.yml
Labels: lang: pt

#569 added French translation of term byte
  glossary.yml
Labels: lang: fr

#538 add definition for 'deep learning' (German)
  glossary.yml
Labels: lang: de

#507 Add definition for "asynchronous" (Greek)
  glossary.yml
Labels: lang: el

#498 Translation for false negative, false positive (Portuguese)
  glossary.yml
Labels: lang: pt
