Repository carpentries/glosario, pull requests merged in 2023-03, with the labels that each got.

#575 Changed 'Chinese' to 中文
  _config.yml
Labels: enhancement

#579 Fix spelling in glossary.yml
  glossary.yml
Labels: lang: en

#578 Translate 1 term (Spanish)
  glossary.yml
Labels: lang: es
