Repository carpentries/glosario, pull requests merged in 2024-09, with the labels that each got.

#696 Translate "debug" to Ukrainian
  glossary.yml
Labels: question, lang: ua, Do not merge

#691 Translate "compile" to Ukrainian
  glossary.yml
Labels: lang: ua, Do not merge

#682 Add Ukrainian translation for "anaconda"
  glossary.yml
Labels: question, lang: ua, Do not merge

#685 Translate "Cache" to Ukrainian
  glossary.yml
Labels: lang: ua, Do not merge

#689 Translate "comment" to Ukrainian
  glossary.yml
Labels: question, lang: ua, Do not merge

#745 Update README.md
  README.md
Labels: enhancement

#748 Add support for externalised sorting per language
  .github/workflows/build-and-deploy.yaml
  .github/workflows/yaml-lint.yaml
  .gitignore
  Makefile
  _includes/glossary.html
  utils/sort-glossary.py
Labels: enhancement
