Repository carpentries/glosario, pull requests merged in 2024-03, with the labels that each got.

#623 Translate autocorrelation to German
  glossary.yml
Labels: lang: de

#621 Translate "aggreation" to German
  glossary.yml
Labels: lang: de

#629 Translating “comment” into Afrikaans
  glossary.yml
Labels: lang: af

#628 Translated "algorithm" to Swahili
  glossary.yml
Labels: lang: sw

#624 Translate "algorithm" into Ukrainian
  glossary.yml
Labels: lang: ua

#622 Translated Bayesian network into Afrikaans
  glossary.yml
Labels: lang: af
