Repository carpentries/glosario, pull requests merged in 2024-05, with the labels that each got.

#641 Translated outlier to Afrikaans
  glossary.yml
Labels: lang: af

#640 Translated group to Afrikaans
  glossary.yml
Labels: lang: af

#639 Translated command to Afrikaans
  glossary.yml
Labels: lang: af

#630 Added French translation for Accuracy
  glossary.yml
Labels: lang: fr

#625 traduccionn to Spanish
  glossary.yml
Labels: lang: es

#626 Translate some ML terms to Spanish
  glossary.yml
Labels: lang: es

#643 Translate 7 terms (Spanish) related to neural networks
  glossary.yml
Labels: lang: es

#649 minor grammatical fix to call stack definition
  glossary.yml
Labels: lang: en

#648 specify that CC0 is a license waiver
  glossary.yml
Labels: lang: en

#650 Translating 3 loop concepts (Spanish)
  glossary.yml
Labels: lang: es

#646 minor fix to CC-BY definition for clarity
  glossary.yml
Labels: lang: en

#647 Spelling and grammar changes to the English terms for letters B, J and K.
  glossary.yml
Labels: lang: en
