Repository carpentries/glosario, pull requests merged in 2024-02, with the labels that each got.

#616 Updated contribution guide
  README.md
Labels: documentation, enhancement

#619 translation to Spanish of the term correlation
  glossary.yml
Labels: lang: es

#618 translation to Spanish of the term Big Data
  glossary.yml
Labels: lang: es

#609 Create la.md
  la.md
Labels: enhancement, lang: la

#610 Included Latin in check-glossary.py
  utils/check-glossary.py
Labels: enhancement, lang: la

#620 Traducción de aliasing al español
  glossary.yml
Labels: lang: es
