Repository carpentries/glosario, pull requests merged in 2024-07, with the labels that each got.

#715 Translate "Whitespace" to Ukrainian
  glossary.yml
Labels: lang: ua

#728 Translate "open_science" to Ukrainian
  glossary.yml
Labels: lang: ua, Do not merge

#731 Translate "HTML" to Ukrainian
  glossary.yml
Labels: lang: ua, Do not merge

#721 Update glossary.yml
  glossary.yml
Labels: lang: en

#634 Translated terms into Afrikaans
  glossary.yml
Labels: lang: af

#729 Translate "orcid" and "doi" to Ukrainian
  glossary.yml
Labels: lang: ua

#733 Translate "README" to Ukrainian
  glossary.yml
Labels: lang: ua, Do not merge

#730 Translate markdown to Ukrainian
  glossary.yml
Labels: lang: ua

#719 Translate "test data" to Ukrainian
  glossary.yml
Labels: lang: ua, Do not merge

#720 Translate "training data" to Ukrainian
  glossary.yml
Labels: lang: ua, Do not merge

#693 Translate "cpu" to Ukrainian
  glossary.yml
Labels: lang: ua

#699 Translated "bug" related words to Ukrainian
  glossary.yml
Labels: lang: ua

#681 Translate "Dictionary" to Ukrainian
  glossary.yml
Labels: lang: ua

#704 Translate "browser_cache" to Ukrainian
  glossary.yml
Labels: lang: ua

#734 Translated class related terms to Ukrainian
  glossary.yml
Labels: lang: ua

#737 Translate "folder" to Ukrainian
  glossary.yml
Labels: lang: ua, Do not merge

#738 Minor spelling mistake
  glossary.yml
Labels: lang: ua

#736 Translate "command_line_argument" to Ukrainian
  glossary.yml
Labels: lang: ua, Do not merge

#711 Translating "histogram", "accuracy", "correlation" and "correlation coefficient" into Ukrainian
  glossary.yml
Labels: lang: ua, Do not merge

#739 Change capitalisation in Ukrainian translation of "dictionary"
  glossary.yml
Labels: lang: ua, Do not merge

#732 Translate "pandas" to Ukrainian
  glossary.yml
Labels: lang: ua, Do not merge
