Repository carpentries/glosario, pull requests merged in 2024-06, with the labels that each got.

#655 Added Ukrainian translation for the term "asynchronous"
  glossary.yml
Labels: lang: ua

#660 Translated "Unicode" to Ukrainian
  glossary.yml
Labels: lang: ua

#657 Add missing word to Ukrainian translation of "algorithm"
  glossary.yml
Labels: lang: ua

#642 Add Ukrainian description of Glosario
  _config.yml
Labels: lang: ua

#663 Translate "AI" to Ukrainian
  glossary.yml
Labels: lang: ua

#664 Translate "GPU" into Ukrainian
  glossary.yml
Labels: lang: ua

#651 Translating "string" into Ukrainian
  glossary.yml
Labels: lang: ua

#668 Translate "remote login" to Ukrainian.
  glossary.yml
Labels: lang: ua

#688 Translate "command" to Ukrainian
  glossary.yml
Labels: lang: ua

#666 Translate "Absolute Path" to Ukrainian
  glossary.yml
Labels: lang: ua

#659 Translated "ASCII" to Ukrainian
  glossary.yml
Labels: lang: ua

#667 Translated "SSH" and "SSH key" to Ukrainian
  glossary.yml
Labels: lang: ua

#701 Corrected the term AI
  glossary.yml
Labels: lang: ua

#679 Translate "Commit_message" to Ukrainian
  glossary.yml
Labels: lang: ua

#665 Translate "JSON" to Ukrainian
  glossary.yml
Labels: lang: ua

#661 Translate "UTF-8" to Ukrainian
  glossary.yml
Labels: lang: ua

#686 Translate "caching" to Ukrainian
  glossary.yml
Labels: lang: ua

#695 Translate "csv" to Ukrainian
  glossary.yml
Labels: lang: ua

#702 Translate "Directory" to Ukrainian
  glossary.yml
Labels: lang: ua

#705 Translate "OOP" to Ukrainian
  glossary.yml
Labels: lang: ua

#672 Translate "Boolean" to Ukrainian
  glossary.yml
Labels: lang: ua

#644 Fix links throughout, mostly around the term 'shader'
  glossary.yml
Labels: lang: en

#671 Translate "loop" to Ukrainian
  glossary.yml
Labels: lang: ua

#645 Edit English Terms
  glossary.yml
Labels: lang: en

#703 Translate "branch" to Ukrainian
  glossary.yml
Labels: lang: ua

#717 Translating terms into German
  glossary.yml
Labels: lang: de

#684 Translate "Binary" to Ukrainian
  glossary.yml
Labels: lang: ua

#678 Translate "Bit" to Ukrainian
  glossary.yml
Labels: lang: ua

#677 Translate "Breadcrumbs" to Ukrainian
  glossary.yml
Labels: lang: ua

#631 Translated autocorrelation into Afrikaans
  glossary.yml
Labels: lang: af

#638 Translated CPU into Afrikaans
  glossary.yml
Labels: lang: af

#714 Translate "code coverage" to Ukrainian
  glossary.yml
Labels: lang: ua

#708 Translate "camel case" to Ukrainian
  glossary.yml
Labels: lang: ua

#632 Translated terms into Afrikaans
  glossary.yml
Labels: lang: af

#707 Translate "call stack" in Ukrainian
  glossary.yml
Labels: lang: ua

#654 Translated API to Ukrainian
  glossary.yml
Labels: lang: ua

#716 Translate "source_code" to Ukrainian
  glossary.yml
Labels: lang: ua

#662 Translated "Backward Compatibility" to Ukrainian
  glossary.yml
Labels: lang: ua

#710 Translate "compute shader" and "shader" to Ukrainian
  glossary.yml
Labels: lang: ua

#713 Translate "catch" to Ukrainian
  glossary.yml
Labels: lang: ua

#709 Translate "filesystem" to Ukrainian
  glossary.yml
Labels: lang: ua

#706 Translated all git related terms to Ukrainian
  glossary.yml
Labels: lang: ua

#658 Translate "argument" to Ukrainian
  glossary.yml
Labels: lang: ua

#727 Translate "cognitive_load" to Ukrainian
  glossary.yml
Labels: lang: ua

#726 Translate "code_review" to Ukrainian
  glossary.yml
Labels: lang: ua

#712 Translate "big data" to Ukrainian
  glossary.yml
Labels: lang: ua, Do not merge

#676 Translate "Byte" to Ukrainian
  glossary.yml
Labels: lang: ua

#669 Translate agile to Ukrainian
  glossary.yml
Labels: lang: ua

#700 Translate compiled_language, interpreted_language, interpreter to Ukrainian
  glossary.yml
Labels: lang: ua
