Repository carpentries/glosario, pull requests merged in 2025-06, with the labels that each got.

#1024 Translate block comment to Afrikaans
  glossary.yml
Labels: lang: af

#1023 Translated down-vote into Afrikaans
  glossary.yml
Labels: lang: af

#1026 Translated Call Stack into French
  glossary.yml
Labels: lang: fr

#774 Translate four statistics terms into Ukrainian
  glossary.yml
Labels: lang: ua
