Repository carpentries/glosario, pull requests merged in 2025-05, with the labels that each got.

#1006 Translate some data terms into Ukrainian
  glossary.yml
Labels: lang: ua

#757 Translate "License" into Ukrainian
  glossary.yml
Labels: lang: ua, Do not merge

#775 Translate four licensing-related terms into Ukrainian
  glossary.yml
Labels: lang: ua, Do not merge

#694 Translate "cran" to Ukrainian
  glossary.yml
Labels: lang: ua

#1010 Add menu navbar, update bootstrap JS
  _includes/table.html
  _includes/title.html
  _layouts/glossary.html
  _layouts/page.html
  assets/css/bootstrap/js/index.esm.js
  assets/css/bootstrap/js/index.umd.js
  assets/css/bootstrap/js/src/alert.js
  assets/css/bootstrap/js/src/base-component.js
  assets/css/bootstrap/js/src/button.js
  assets/css/bootstrap/js/src/carousel.js
  assets/css/bootstrap/js/src/collapse.js
  assets/css/bootstrap/js/src/dom/data.js
  assets/css/bootstrap/js/src/dom/event-handler.js
  assets/css/bootstrap/js/src/dom/manipulator.js
  assets/css/bootstrap/js/src/dom/selector-engine.js
  assets/css/bootstrap/js/src/dropdown.js
  assets/css/bootstrap/js/src/modal.js
  assets/css/bootstrap/js/src/offcanvas.js
  assets/css/bootstrap/js/src/popover.js
  assets/css/bootstrap/js/src/scrollspy.js
  assets/css/bootstrap/js/src/tab.js
  assets/css/bootstrap/js/src/toast.js
  assets/css/bootstrap/js/src/tooltip.js
  assets/css/bootstrap/js/src/util/backdrop.js
  assets/css/bootstrap/js/src/util/component-functions.js
  assets/css/bootstrap/js/src/util/config.js
  assets/css/bootstrap/js/src/util/focustrap.js
  assets/css/bootstrap/js/src/util/index.js
  assets/css/bootstrap/js/src/util/sanitizer.js
  assets/css/bootstrap/js/src/util/scrollbar.js
  assets/css/bootstrap/js/src/util/swipe.js
  assets/css/bootstrap/js/src/util/template-factory.js
  assets/css/glossary.scss
  assets/js/bootstrap/bootstrap.bundle.min.js
  assets/js/bootstrap/bootstrap.bundle.min.js.map
  help.md
  index.html
  utils/sort-glossary.py
Labels: enhancement

#1009 Update README.md
  README.md
Labels: documentation
